// A large pool of short "thinking" phrases shown while a reply is in flight.
// The vibe is a playful developer/terminal REPL — deliberately generic so it
// carries no third-party branding. One is picked at random each time the
// indicator appears, and it rotates through more during longer waits.

export const THINKING_PHRASES: string[] = [
  'Thinking…',
  'One sec…',
  'Pondering…',
  'Noodling on it…',
  'Ruminating…',
  'Mulling it over…',
  'Cogitating…',
  'Percolating…',
  'Untangling that…',
  'Connecting the dots…',
  'Pulling that together…',
  'Let me check that…',
  'Digging in…',
  'Almost there…',
  'Warming up the neurons…',
  'Consulting the archives…',
  'Reading the notes…',
  'Cross-referencing…',
  'Grounding the facts…',
  'Fetching context…',
  'Loading context…',
  'Indexing thoughts…',
  'Parsing your question…',
  'Compiling a reply…',
  'Assembling the answer…',
  'Formulating…',
  'Composing…',
  'Drafting…',
  'Sketching it out…',
  'Wiring it up…',
  'Threading the needle…',
  'Doing the math…',
  'Crunching…',
  'Reticulating splines…',
  'Traversing the graph…',
  'Walking the knowledge tree…',
  'Querying the memory…',
  'Spinning up…',
  'Booting a thought…',
  'Caching the details…',
  'Tidying the response…',
  'Polishing…',
  'Refining…',
  'Double-checking…',
  'Fact-checking myself…',
  'Weighing the options…',
  'Considering angles…',
  'Joining the pieces…',
  'Summoning specifics…',
  'Recalling the details…',
  'Flipping through the portfolio…',
  'Scanning the projects…',
  'Skimming the résumé…',
  'Lining up the highlights…',
  'Finding the good parts…',
  'Picking the best example…',
  'Getting my bearings…',
  'Gathering receipts…',
  'Sorting the signal…',
  'Distilling it…',
  'Boiling it down…',
  'Zooming in…',
  'Focusing…',
  'Tracing the thread…',
  'Following the logic…',
  'Reasoning it through…',
  'Working it out…',
  'Puzzling it out…',
  'Chewing on it…',
  'Turning it over…',
  'Letting it marinate…',
  'Brewing a reply…',
  'Steeping…',
  'Simmering…',
  'Cooking…',
  'Plating the answer…',
  'Wordsmithing…',
  'Choosing my words…',
  'Phrasing it well…',
  'Making it make sense…',
  'Keeping it concise…',
  'Trimming the fat…',
  'Sharpening the point…',
  'Adding the nuance…',
  'Checking the specifics…',
  'Verifying the numbers…',
  'Lining up the dates…',
  'Confirming the details…',
  'Loading the details…',
  'Rummaging through notes…',
  'Flipping to the right page…',
  'Bookmarking the essentials…',
  'Highlighting the wins…',
  'Curating the answer…',
  'Handpicking the facts…',
  'Reasoning…',
  'Deliberating…',
  'Contemplating…',
  'Reflecting…',
  'Processing…',
  'Computing…',
  'Calculating…',
  'Synthesizing…',
  'Aggregating…',
  'Collating…',
  'Organizing my thoughts…',
  'Structuring the reply…',
  'Outlining…',
  'Mapping it out…',
  'Piecing it together…',
  'Stitching it up…',
  'Bringing it home…',
  'Wrapping up…',
  'Rounding it off…',
  'Finishing the thought…',
  'Landing the point…',
  'Tuning the phrasing…',
  'Reviewing once more…',
  'Giving it a once-over…',
  'Making it click…',
  'Nearly there…',
  'Hang tight…',
  'Bear with me…',
  'Just a moment…',
]

/** Returns a random thinking phrase from the pool. */
export function randomThinking(): string {
  return THINKING_PHRASES[Math.floor(Math.random() * THINKING_PHRASES.length)]
}
